services:
  - type: web
    name: mini-qgis-online
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8000
