version: '3'

services:

  postgis:
    image: postgis/postgis
    environment:
      POSTGRES_DB: gis
      POSTGRES_USER: gis
      POSTGRES_PASSWORD: gis
    ports:
      - "5432:5432"

  geoserver:
    build: ./geoserver
    ports:
      - "8080:8080"
    depends_on:
      - postgis

  backend:
    build: ../backend
    ports:
      - "5000:5000"